### ISSUE TITLE
请问下面的按钮点击相应想要重写应该在哪写

### ISSUE THREAD

**Issue by zzz0906** [yaochangliang159/Android-TabView#1]
请问下面的按钮点击相应想要重写应该在哪写
也就是每一个list的按钮点击要重写应该怎么重写

**Comment by yaochangliang159** [comment]
在TabView的264行点击事件，，你自己改一下吧。。

**Comment by zzz0906** [comment]
@yaochangliang159  还有请问如果在一个fragement调用键盘事件 发现那个tabview导航栏会上挪

**Comment by yaochangliang159** [comment]
在Manifest里面设置你的当前activity    android:windowSoftInputMode=""模式你自己修改，这个和你activity的windowSoftInputMode有关，和TabView这个库没关系

**Comment by zzz0906** [comment]
哦哦 好的谢谢
